[build]
  command = "yarn run build"
  base = "/"
  publish = "dist"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[plugins]]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  buildDir = "dist"